export const cities = [
  'Aleksandrów Kujawski',
  'Aleksandrów Łódzki',
  'Alwernia',
  'Andrychów',
  'Annopol (lubelskie)',
  'Augustów (podlaskie)',
  'Babimost',
  'Baborów',
  'Baranów Sandomierski',
  'Barcin',
  'Barczewo',
  'Bardo (dolnośląskie)',
  'Barlinek',
  'Bartoszyce',
  'Barwice',
  'Bełchatów',
  'Bełżyce',
  'Będzin (śląskie)',
  'Biała (opolskie)',
  'Biała Piska',
  'Biała Podlaska',
  'Biała Rawska',
  'Białobrzegi (mazowieckie)',
  'Białogard',
  'Biały Bór (zachodniopomorskie)',
  'Białystok (podlaskie)',
  'Biecz (małopolskie)',
  'Bielawa (dolnośląskie)',
  'Bielsk Podlaski',
  'Bielsko-Biała',
  'Bieruń',
  'Bierutów',
  'Bieżuń',
  'Biłgoraj (lubelskie)',
  'Biskupiec (warmińsko-mazurskie)',
  'Bisztynek',
  'Blachownia (śląskie)',
  'Błaszki',
  'Błażowa',
  'Błonie (mazowieckie)',
  'Bobolice (zachodniopomorskie)',
  'Bobowa',
  'Bochnia (małopolskie)',
  'Bodzentyn',
  'Bogatynia',
  'Boguchwała (podkarpackie)',
  'Boguszów-Gorce',
  'Bojanowo (wielkopolskie)',
  'Bolesławiec (dolnośląskie)',
  'Bolków (dolnośląskie)',
  'Borek Wielkopolski',
  'Borne Sulinowo',
  'Braniewo',
  'Brańsk',
  'Brodnica (kujawsko-pomorskie)',
  'Brok (mazowieckie)',
  'Brusy',
  'Brwinów',
  'Brzeg (opolskie)',
  'Brzeg Dolny',
  'Brzesko (małopolskie)',
  'Brzeszcze',
  'Brześć Kujawski',
  'Brzeziny (łódzkie)',
  'Brzostek (podkarpackie)',
  'Brzozów (podkarpackie)',
  'Buk (wielkopolskie)',
  'Bukowno (małopolskie)',
  'Busko-Zdrój',
  'Bychawa',
  'Byczyna (opolskie)',
  'Bydgoszcz (kujawsko-pomorskie)',
  'Bystrzyca Kłodzka',
  'Bytom',
  'Bytom Odrzański',
  'Bytów',
  'Cedynia',
  'Chełm (lubelskie)',
  'Chełmek (małopolskie)',
  'Chełmno (kujawsko-pomorskie)',
  'Chełmża',
  'Chęciny (świętokrzyskie)',
  'Chmielnik (świętokrzyskie)',
  'Chocianów',
  'Chociwel (zachodniopomorskie)',
  'Chocz',
  'Chodecz',
  'Chodzież',
  'Chojna (zachodniopomorskie)',
  'Chojnice',
  'Chojnów (dolnośląskie)',
  'Choroszcz',
  'Chorzele (mazowieckie)',
  'Chorzów (śląskie)',
  'Choszczno',
  'Chrzanów (małopolskie)',
  'Ciechanowiec',
  'Ciechanów (mazowieckie)',
  'Ciechocinek',
  'Cieszanów',
  'Cieszyn (śląskie)',
  'Ciężkowice (małopolskie)',
  'Cybinka',
  'Czaplinek (zachodniopomorskie)',
  'Czarna Białostocka',
  'Czarna Woda (pomorskie)',
  'Czarne (pomorskie)',
  'Czarnków (wielkopolskie)',
  'Czchów',
  'Czechowice-Dziedzice',
  'Czeladź',
  'Czempiń',
  'Czerniejewo',
  'Czersk (pomorskie)',
  'Czerwieńsk',
  'Czerwionka-Leszczyny',
  'Częstochowa',
  'Człopa',
  'Człuchów',
  'Czyżew (podlaskie)',
  'Ćmielów',
  'Daleszyce (świętokrzyskie)',
  'Darłowo',
  'Dąbie (wielkopolskie)',
  'Dąbrowa Białostocka',
  'Dąbrowa Górnicza',
  'Dąbrowa Tarnowska',
  'Debrzno',
  'Dębica (podkarpackie)',
  'Dęblin',
  'Dębno (zachodniopomorskie)',
  'Dobczyce (małopolskie)',
  'Dobiegniew (lubuskie)',
  'Dobra (wielkopolskie)',
  'Dobra (zachodniopomorskie)',
  'Dobre Miasto',
  'Dobrodzień',
  'Dobrzany (zachodniopomorskie)',
  'Dobrzyca (wielkopolskie)',
  'Dobrzyń nad Wisłą',
  'Dolsk (wielkopolskie)',
  'Drawno',
  'Drawsko Pomorskie',
  'Drezdenko',
  'Drobin',
  'Drohiczyn',
  'Drzewica (łódzkie)',
  'Dukla (podkarpackie)',
  'Duszniki-Zdrój',
  'Dynów',
  'Działdowo',
  'Działoszyce (świętokrzyskie)',
  'Działoszyn (łódzkie)',
  'Dzierzgoń',
  'Dzierżoniów',
  'Dziwnów',
  'Elbląg',
  'Ełk (warmińsko-mazurskie)',
  'Frampol',
  'Frombork',
  'Garwolin (mazowieckie)',
  'Gąbin (mazowieckie)',
  'Gdańsk (pomorskie)',
  'Gdynia (pomorskie)',
  'Giżycko',
  'Glinojeck',
  'Gliwice',
  'Głogów (dolnośląskie)',
  'Głogów Małopolski',
  'Głogówek',
  'Głowno',
  'Głubczyce',
  'Głuchołazy',
  'Głuszyca (dolnośląskie)',
  'Gniew',
  'Gniewkowo (kujawsko-pomorskie)',
  'Gniezno',
  'Gogolin (opolskie)',
  'Golczewo (zachodniopomorskie)',
  'Goleniów (zachodniopomorskie)',
  'Golina (wielkopolskie)',
  'Golub-Dobrzyń',
  'Gołańcz',
  'Gołdap (warmińsko-mazurskie)',
  'Goniądz',
  'Gorlice',
  'Gorzów Śląski',
  'Gorzów Wielkopolski',
  'Gostynin',
  'Gostyń (wielkopolskie)',
  'Gościno',
  'Gozdnica (lubuskie)',
  'Góra (dolnośląskie)',
  'Góra Kalwaria',
  'Górowo Iławeckie',
  'Górzno (kujawsko-pomorskie)',
  'Grabów nad Prosną',
  'Grajewo (podlaskie)',
  'Grodków (opolskie)',
  'Grodzisk Mazowiecki',
  'Grodzisk Wielkopolski',
  'Grójec (mazowieckie)',
  'Grudziądz',
  'Grybów',
  'Gryfice',
  'Gryfino',
  'Gryfów Śląski',
  'Gubin',
  'Hajnówka (podlaskie)',
  'Halinów (mazowieckie)',
  'Hel',
  'Hrubieszów',
  'Iława (warmińsko-mazurskie)',
  'Iłowa (lubuskie)',
  'Iłża',
  'Imielin (śląskie)',
  'Inowrocław',
  'Ińsko',
  'Iwonicz-Zdrój',
  'Izbica Kujawska',
  'Jabłonowo Pomorskie',
  'Janikowo (kujawsko-pomorskie)',
  'Janowiec Wielkopolski',
  'Janów Lubelski',
  'Jarocin (wielkopolskie)',
  'Jarosław (podkarpackie)',
  'Jasień (lubuskie)',
  'Jasło',
  'Jastarnia',
  'Jastrowie',
  'Jastrzębie-Zdrój',
  'Jawor (dolnośląskie)',
  'Jaworzno (śląskie)',
  'Jaworzyna Śląska',
  'Jedlicze',
  'Jedlina-Zdrój',
  'Jedwabne',
  'Jelcz-Laskowice',
  'Jelenia Góra (dolnośląskie)',
  'Jeziorany',
  'Jędrzejów (świętokrzyskie)',
  'Jordanów (małopolskie)',
  'Józefów (lubelskie)',
  'Józefów (mazowieckie)',
  'Jutrosin (wielkopolskie)',
  'Kalety (śląskie)',
  'Kalisz (wielkopolskie)',
  'Kalisz Pomorski',
  'Kalwaria Zebrzydowska',
  'Kałuszyn (mazowieckie)',
  'Kamienna Góra (dolnośląskie)',
  'Kamień Krajeński',
  'Kamień Pomorski',
  'Kamieńsk (łódzkie)',
  'Kańczuga (podkarpackie)',
  'Karczew (mazowieckie)',
  'Kargowa',
  'Karlino',
  'Karpacz',
  'Kartuzy (pomorskie)',
  'Katowice',
  'Kazimierz Dolny',
  'Kazimierza Wielka',
  'Kąty Wrocławskie',
  'Kcynia',
  'Kędzierzyn-Koźle',
  'Kępice (pomorskie)',
  'Kępno (wielkopolskie)',
  'Kętrzyn',
  'Kęty',
  'Kielce',
  'Kietrz',
  'Kisielice (warmińsko-mazurskie)',
  'Kleczew',
  'Kleszczele',
  'Kluczbork',
  'Kłecko',
  'Kłobuck',
  'Kłodawa (wielkopolskie)',
  'Kłodzko',
  'Knurów (śląskie)',
  'Knyszyn (podlaskie)',
  'Kobylin (wielkopolskie)',
  'Kobyłka (mazowieckie)',
  'Kock (lubelskie)',
  'Kolbuszowa (podkarpackie)',
  'Kolno (podlaskie)',
  'Kolonowskie',
  'Koluszki',
  'Kołaczyce',
  'Koło (wielkopolskie)',
  'Kołobrzeg',
  'Koniecpol (śląskie)',
  'Konin (wielkopolskie)',
  'Konstancin-Jeziorna',
  'Konstantynów Łódzki',
  'Końskie (świętokrzyskie)',
  'Koprzywnica (świętokrzyskie)',
  'Korfantów',
  'Koronowo (kujawsko-pomorskie)',
  'Korsze',
  'Kosów Lacki',
  'Kostrzyn (wielkopolskie)',
  'Kostrzyn nad Odrą',
  'Koszalin',
  'Kościan',
  'Kościerzyna',
  'Kowal',
  'Kowalewo Pomorskie',
  'Kowary (dolnośląskie)',
  'Koziegłowy (śląskie)',
  'Kozienice (mazowieckie)',
  'Koźmin Wielkopolski',
  'Kożuchów (lubuskie)',
  'Kórnik',
  'Krajenka',
  'Kraków (małopolskie)',
  'Krapkowice',
  'Krasnobród',
  'Krasnystaw',
  'Kraśnik (lubelskie)',
  'Krobia (wielkopolskie)',
  'Krosno (podkarpackie)',
  'Krosno Odrzańskie',
  'Krośniewice',
  'Krotoszyn (wielkopolskie)',
  'Kruszwica',
  'Krynica Morska',
  'Krynica-Zdrój',
  'Krynki (podlaskie)',
  'Krzanowice (śląskie)',
  'Krzepice (śląskie)',
  'Krzeszowice',
  'Krzywiń',
  'Krzyż Wielkopolski',
  'Książ Wielkopolski',
  'Kudowa-Zdrój',
  'Kunów (świętokrzyskie)',
  'Kutno',
  'Kuźnia Raciborska',
  'Kwidzyn',
  'Lądek-Zdrój',
  'Legionowo (mazowieckie)',
  'Legnica',
  'Lesko',
  'Leszno (wielkopolskie)',
  'Leśna (dolnośląskie)',
  'Leśnica (opolskie)',
  'Lewin Brzeski',
  'Leżajsk',
  'Lębork',
  'Lędziny (śląskie)',
  'Libiąż (małopolskie)',
  'Lidzbark',
  'Lidzbark Warmiński',
  'Limanowa',
  'Lipiany (zachodniopomorskie)',
  'Lipno (kujawsko-pomorskie)',
  'Lipsk',
  'Lipsko (mazowieckie)',
  'Lubaczów',
  'Lubań (dolnośląskie)',
  'Lubartów (lubelskie)',
  'Lubawa',
  'Lubawka (dolnośląskie)',
  'Lubień Kujawski',
  'Lubin (dolnośląskie)',
  'Lublin',
  'Lubliniec',
  'Lubniewice',
  'Lubomierz (dolnośląskie)',
  'Luboń (wielkopolskie)',
  'Lubraniec',
  'Lubsko',
  'Lwówek (wielkopolskie)',
  'Lwówek Śląski',
  'Łabiszyn (kujawsko-pomorskie)',
  'Łańcut',
  'Łapy',
  'Łasin',
  'Łask',
  'Łaskarzew',
  'Łaszczów',
  'Łaziska Górne',
  'Łazy (śląskie)',
  'Łeba',
  'Łęczna (lubelskie)',
  'Łęczyca (łódzkie)',
  'Łęknica (lubuskie)',
  'Łobez (zachodniopomorskie)',
  'Łobżenica',
  'Łochów (mazowieckie)',
  'Łomianki',
  'Łomża',
  'Łosice (mazowieckie)',
  'Łowicz (łódzkie)',
  'Łódź (łódzkie)',
  'Łuków (lubelskie)',
  'Maków Mazowiecki',
  'Maków Podhalański',
  'Malbork (pomorskie)',
  'Małogoszcz',
  'Małomice (lubuskie)',
  'Margonin',
  'Marki (mazowieckie)',
  'Maszewo (zachodniopomorskie)',
  'Miasteczko Śląskie',
  'Miastko (pomorskie)',
  'Michałowo (podlaskie)',
  'Miechów (małopolskie)',
  'Miejska Górka',
  'Mielec',
  'Mieroszów',
  'Mieszkowice (zachodniopomorskie)',
  'Międzybórz (dolnośląskie)',
  'Międzychód (wielkopolskie)',
  'Międzylesie (dolnośląskie)',
  'Międzyrzec Podlaski',
  'Międzyrzecz',
  'Międzyzdroje',
  'Mikołajki (warmińsko-mazurskie)',
  'Mikołów',
  'Mikstat',
  'Milanówek',
  'Milicz (dolnośląskie)',
  'Miłakowo (warmińsko-mazurskie)',
  'Miłomłyn',
  'Miłosław (wielkopolskie)',
  'Mińsk Mazowiecki',
  'Mirosławiec',
  'Mirsk',
  'Mława',
  'Młynary (warmińsko-mazurskie)',
  'Modliborzyce (lubelskie)',
  'Mogielnica (mazowieckie)',
  'Mogilno (kujawsko-pomorskie)',
  'Mońki',
  'Morąg',
  'Mordy',
  'Moryń',
  'Mosina (wielkopolskie)',
  'Mrągowo',
  'Mrocza',
  'Mrozy (mazowieckie)',
  'Mszana Dolna',
  'Mszczonów',
  'Murowana Goślina',
  'Muszyna',
  'Mysłowice (śląskie)',
  'Myszków',
  'Myszyniec (mazowieckie)',
  'Myślenice (małopolskie)',
  'Myślibórz (zachodniopomorskie)',
  'Nakło nad Notecią',
  'Nałęczów (lubelskie)',
  'Namysłów',
  'Narol',
  'Nasielsk',
  'Nekla (wielkopolskie)',
  'Nidzica',
  'Niemcza (dolnośląskie)',
  'Niemodlin',
  'Niepołomice',
  'Nieszawa (kujawsko-pomorskie)',
  'Nisko (podkarpackie)',
  'Nowa Dęba',
  'Nowa Ruda (dolnośląskie)',
  'Nowa Sarzyna',
  'Nowa Sól',
  'Nowe (kujawsko-pomorskie)',
  'Nowe Brzesko',
  'Nowe Miasteczko',
  'Nowe Miasto Lubawskie',
  'Nowe Miasto nad Pilicą',
  'Nowe Skalmierzyce',
  'Nowe Warpno',
  'Nowogard',
  'Nowogrodziec',
  'Nowogród (podlaskie)',
  'Nowogród Bobrzański',
  'Nowy Dwór Gdański',
  'Nowy Dwór Mazowiecki',
  'Nowy Sącz',
  'Nowy Staw (pomorskie)',
  'Nowy Targ (małopolskie)',
  'Nowy Tomyśl',
  'Nowy Wiśnicz',
  'Nysa',
  'Oborniki',
  'Oborniki Śląskie',
  'Obrzycko',
  'Odolanów (wielkopolskie)',
  'Ogrodzieniec (śląskie)',
  'Okonek',
  'Olecko',
  'Olesno (opolskie)',
  'Oleszyce',
  'Oleśnica (dolnośląskie)',
  'Olkusz',
  'Olsztyn (warmińsko-mazurskie)',
  'Olsztynek',
  'Olszyna (dolnośląskie)',
  'Oława',
  'Opalenica (wielkopolskie)',
  'Opatów (świętokrzyskie)',
  'Opoczno',
  'Opole (opolskie)',
  'Opole Lubelskie',
  'Orneta',
  'Orzesze (śląskie)',
  'Orzysz',
  'Osieczna (wielkopolskie)',
  'Osiek (świętokrzyskie)',
  'Ostrołęka (mazowieckie)',
  'Ostroróg (wielkopolskie)',
  'Ostrowiec Świętokrzyski',
  'Ostróda',
  'Ostrów Lubelski',
  'Ostrów Mazowiecka',
  'Ostrów Wielkopolski',
  'Ostrzeszów',
  'Ośno Lubuskie',
  'Oświęcim (małopolskie)',
  'Otmuchów',
  'Otwock (mazowieckie)',
  'Ozimek',
  'Ozorków',
  'Ożarów (świętokrzyskie)',
  'Ożarów Mazowiecki',
  'Pabianice (łódzkie)',
  'Paczków (opolskie)',
  'Pajęczno (łódzkie)',
  'Pakość (kujawsko-pomorskie)',
  'Parczew (lubelskie)',
  'Pasłęk',
  'Pasym (warmińsko-mazurskie)',
  'Pelplin',
  'Pełczyce (zachodniopomorskie)',
  'Piaseczno (mazowieckie)',
  'Piaski (lubelskie)',
  'Piastów (mazowieckie)',
  'Piechowice (dolnośląskie)',
  'Piekary Śląskie',
  'Pieniężno (warmińsko-mazurskie)',
  'Pieńsk',
  'Pieszyce',
  'Pilawa (mazowieckie)',
  'Pilica (śląskie)',
  'Pilzno',
  'Piła (wielkopolskie)',
  'Piława Górna',
  'Pińczów (świętokrzyskie)',
  'Pionki (mazowieckie)',
  'Piotrków Kujawski',
  'Piotrków Trybunalski',
  'Pisz',
  'Piwniczna-Zdrój',
  'Pleszew',
  'Płock',
  'Płońsk',
  'Płoty (zachodniopomorskie)',
  'Pniewy (wielkopolskie)',
  'Pobiedziska',
  'Poddębice (łódzkie)',
  'Podkowa Leśna',
  'Pogorzela (wielkopolskie)',
  'Polanica-Zdrój',
  'Polanów (zachodniopomorskie)',
  'Police (zachodniopomorskie)',
  'Polkowice',
  'Połaniec',
  'Połczyn-Zdrój',
  'Poniatowa (lubelskie)',
  'Poniec',
  'Poręba (śląskie)',
  'Poznań (wielkopolskie)',
  'Prabuty (pomorskie)',
  'Praszka',
  'Prochowice',
  'Proszowice',
  'Prószków',
  'Pruchnik',
  'Prudnik',
  'Prusice (dolnośląskie)',
  'Pruszcz Gdański',
  'Pruszków (mazowieckie)',
  'Przasnysz',
  'Przecław (podkarpackie)',
  'Przedbórz (łódzkie)',
  'Przedecz',
  'Przemków',
  'Przemyśl (podkarpackie)',
  'Przeworsk',
  'Przysucha',
  'Pszczyna',
  'Pszów',
  'Puck (pomorskie)',
  'Puławy (lubelskie)',
  'Pułtusk',
  'Puszczykowo (wielkopolskie)',
  'Pyrzyce',
  'Pyskowice (śląskie)',
  'Pyzdry',
  'Rabka-Zdrój',
  'Raciąż (mazowieckie)',
  'Racibórz (śląskie)',
  'Radków (dolnośląskie)',
  'Radlin (śląskie)',
  'Radłów (małopolskie)',
  'Radom (mazowieckie)',
  'Radomsko',
  'Radomyśl Wielki',
  'Radymno',
  'Radziejów (kujawsko-pomorskie)',
  'Radzionków',
  'Radzymin (mazowieckie)',
  'Radzyń Chełmiński',
  'Radzyń Podlaski',
  'Rajgród (podlaskie)',
  'Rakoniewice (wielkopolskie)',
  'Raszków (wielkopolskie)',
  'Rawa Mazowiecka',
  'Rawicz (wielkopolskie)',
  'Recz (zachodniopomorskie)',
  'Reda',
  'Rejowiec Fabryczny',
  'Resko',
  'Reszel',
  'Rogoźno (wielkopolskie)',
  'Ropczyce',
  'Różan',
  'Ruciane-Nida',
  'Ruda Śląska',
  'Rudnik nad Sanem',
  'Rumia',
  'Rybnik (śląskie)',
  'Rychwał',
  'Rydułtowy',
  'Rydzyna (wielkopolskie)',
  'Ryglice',
  'Ryki (lubelskie)',
  'Rymanów',
  'Ryn (warmińsko-mazurskie)',
  'Rypin',
  'Rzepin (lubuskie)',
  'Rzeszów',
  'Rzgów (łódzkie)',
  'Sandomierz',
  'Sanok',
  'Sejny',
  'Serock (mazowieckie)',
  'Sędziszów',
  'Sędziszów Małopolski',
  'Sępopol',
  'Sępólno Krajeńskie',
  'Sianów',
  'Siechnice',
  'Siedlce (mazowieckie)',
  'Siemianowice Śląskie',
  'Siemiatycze',
  'Sieniawa (podkarpackie)',
  'Sieradz (łódzkie)',
  'Sieraków (wielkopolskie)',
  'Sierpc',
  'Siewierz',
  'Skalbmierz',
  'Skała (małopolskie)',
  'Skarszewy (pomorskie)',
  'Skaryszew',
  'Skarżysko-Kamienna',
  'Skawina',
  'Skępe',
  'Skierniewice',
  'Skoczów (śląskie)',
  'Skoki (wielkopolskie)',
  'Skórcz',
  'Skwierzyna',
  'Sława (lubuskie)',
  'Sławków (śląskie)',
  'Sławno (zachodniopomorskie)',
  'Słomniki',
  'Słubice (lubuskie)',
  'Słupca (wielkopolskie)',
  'Słupsk',
  'Sobótka (dolnośląskie)',
  'Sochaczew',
  'Sokołów Małopolski',
  'Sokołów Podlaski',
  'Sokółka (podlaskie)',
  'Solec Kujawski',
  'Sompolno',
  'Sopot',
  'Sosnowiec (śląskie)',
  'Sośnicowice',
  'Stalowa Wola',
  'Starachowice',
  'Stargard Szczeciński',
  'Starogard Gdański',
  'Stary Sącz',
  'Staszów (świętokrzyskie)',
  'Stawiski',
  'Stawiszyn (wielkopolskie)',
  'Stąporków',
  'Stepnica',
  'Stęszew',
  'Stoczek Łukowski',
  'Stopnica',
  'Stronie Śląskie (dolnośląskie)',
  'Strumień (śląskie)',
  'Stryków (łódzkie)',
  'Strzegom (dolnośląskie)',
  'Strzelce Krajeńskie',
  'Strzelce Opolskie',
  'Strzelin',
  'Strzelno (kujawsko-pomorskie)',
  'Strzyżów (podkarpackie)',
  'Sucha Beskidzka',
  'Suchań',
  'Suchedniów',
  'Suchowola (podlaskie)',
  'Sulechów (lubuskie)',
  'Sulejów (łódzkie)',
  'Sulejówek (mazowieckie)',
  'Sulęcin (lubuskie)',
  'Sulmierzyce (wielkopolskie)',
  'Sułkowice (małopolskie)',
  'Supraśl',
  'Suraż',
  'Susz',
  'Suwałki (podlaskie)',
  'Swarzędz',
  'Syców',
  'Szadek (łódzkie)',
  'Szamocin (wielkopolskie)',
  'Szamotuły',
  'Szczawnica',
  'Szczawno-Zdrój',
  'Szczebrzeszyn',
  'Szczecin (zachodniopomorskie)',
  'Szczecinek',
  'Szczekociny',
  'Szczucin',
  'Szczuczyn (podlaskie)',
  'Szczyrk',
  'Szczytna (dolnośląskie)',
  'Szczytno (warmińsko-mazurskie)',
  'Szepietowo',
  'Szklarska Poręba',
  'Szlichtyngowa',
  'Szprotawa',
  'Sztum',
  'Szubin',
  'Szydłowiec (mazowieckie)',
  'Ścinawa (dolnośląskie)',
  'Ślesin (wielkopolskie)',
  'Śmigiel',
  'Śrem (wielkopolskie)',
  'Środa Śląska',
  'Środa Wielkopolska',
  'Świątniki Górne',
  'Świdnica (dolnośląskie)',
  'Świdnik (lubelskie)',
  'Świdwin',
  'Świebodzice',
  'Świebodzin (lubuskie)',
  'Świecie (kujawsko-pomorskie)',
  'Świeradów-Zdrój',
  'Świerzawa',
  'Świętochłowice',
  'Świnoujście',
  'Tarczyn (mazowieckie)',
  'Tarnobrzeg',
  'Tarnogród',
  'Tarnowskie Góry',
  'Tarnów (małopolskie)',
  'Tczew',
  'Terespol (lubelskie)',
  'Tłuszcz (mazowieckie)',
  'Tolkmicko',
  'Tomaszów Lubelski',
  'Tomaszów Mazowiecki',
  'Toruń (kujawsko-pomorskie)',
  'Torzym',
  'Toszek',
  'Trzcianka (wielkopolskie)',
  'Trzciel (lubuskie)',
  'Trzcińsko-Zdrój',
  'Trzebiatów (zachodniopomorskie)',
  'Trzebinia (małopolskie)',
  'Trzebnica',
  'Trzemeszno (wielkopolskie)',
  'Tuchola (kujawsko-pomorskie)',
  'Tuchów',
  'Tuczno (zachodniopomorskie)',
  'Tuliszków',
  'Turek (wielkopolskie)',
  'Tuszyn (łódzkie)',
  'Twardogóra',
  'Tychowo (zachodniopomorskie)',
  'Tychy',
  'Tyczyn (podkarpackie)',
  'Tykocin',
  'Tyszowce',
  'Ujazd (opolskie)',
  'Ujście (wielkopolskie)',
  'Ulanów (podkarpackie)',
  'Uniejów',
  'Ustka',
  'Ustroń (śląskie)',
  'Ustrzyki Dolne',
  'Wadowice',
  'Wałbrzych',
  'Wałcz',
  'Warka',
  'Warszawa (mazowieckie)',
  'Warta (łódzkie)',
  'Wasilków',
  'Wąbrzeźno',
  'Wąchock',
  'Wągrowiec',
  'Wąsosz (dolnośląskie)',
  'Wejherowo',
  'Węgliniec',
  'Węgorzewo (warmińsko-mazurskie)',
  'Węgorzyno (zachodniopomorskie)',
  'Węgrów (mazowieckie)',
  'Wiązów',
  'Wieleń (wielkopolskie)',
  'Wielichowo (wielkopolskie)',
  'Wieliczka (małopolskie)',
  'Wieluń (łódzkie)',
  'Wieruszów (łódzkie)',
  'Więcbork',
  'Wilamowice (śląskie)',
  'Wisła (śląskie)',
  'Witkowo (wielkopolskie)',
  'Witnica (lubuskie)',
  'Wleń',
  'Władysławowo (pomorskie)',
  'Włocławek',
  'Włodawa',
  'Włoszczowa (świętokrzyskie)',
  'Wodzisław Śląski',
  'Wojcieszów',
  'Wojkowice (śląskie)',
  'Wojnicz',
  'Wolbórz',
  'Wolbrom',
  'Wolin',
  'Wolsztyn',
  'Wołczyn (opolskie)',
  'Wołomin',
  'Wołów (dolnośląskie)',
  'Woźniki (śląskie)',
  'Wrocław',
  'Wronki (wielkopolskie)',
  'Września (wielkopolskie)',
  'Wschowa',
  'Wyrzysk',
  'Wysoka (wielkopolskie)',
  'Wysokie Mazowieckie',
  'Wyszków (mazowieckie)',
  'Wyszogród (mazowieckie)',
  'Wyśmierzyce',
  'Zabłudów',
  'Zabrze (śląskie)',
  'Zagórów (wielkopolskie)',
  'Zagórz (podkarpackie)',
  'Zakliczyn (małopolskie)',
  'Zaklików',
  'Zakopane (małopolskie)',
  'Zakroczym',
  'Zalewo (warmińsko-mazurskie)',
  'Zambrów',
  'Zamość (lubelskie)',
  'Zator (małopolskie)',
  'Zawadzkie',
  'Zawichost',
  'Zawidów',
  'Zawiercie',
  'Ząbki (mazowieckie)',
  'Ząbkowice Śląskie',
  'Zbąszynek',
  'Zbąszyń',
  'Zduny (wielkopolskie)',
  'Zduńska Wola',
  'Zdzieszowice',
  'Zelów',
  'Zgierz (łódzkie)',
  'Zgorzelec (dolnośląskie)',
  'Zielona Góra (lubuskie)',
  'Zielonka (mazowieckie)',
  'Ziębice',
  'Złocieniec',
  'Złoczew',
  'Złotoryja (dolnośląskie)',
  'Złotów (wielkopolskie)',
  'Złoty Stok',
  'Zwierzyniec (lubelskie)',
  'Zwoleń (mazowieckie)',
  'Żabno (małopolskie)',
  'Żagań',
  'Żarki (śląskie)',
  'Żarów (dolnośląskie)',
  'Żary (lubuskie)',
  'Żelechów (mazowieckie)',
  'Żerków (wielkopolskie)',
  'Żmigród (dolnośląskie)',
  'Żnin',
  'Żory (śląskie)',
  'Żukowo (pomorskie)',
  'Żuromin',
  'Żychlin (łódzkie)',
  'Żyrardów',
  'Żywiec',
];
